services:
  bot:
    image: ghcr.io/shard-hq/shard:latest
    container_name: shard
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/usr/src/app/data

volumes:
  data:
